#!/usr/bin/env bash

PKG_PATH="$1"
PKG_NAME=${PKG_PATH##*/}

if [[ -z "$PKG_NAME" ]]; then
    echo "incorrect package path: $PKG_PATH"
    exit 1
fi

if [[ ! "$PKG_NAME" =~ ^[a-zA-Z0-9_-]+$ ]]; then
    echo "incorrect package name: $PKG_NAME"
    exit 1
fi

IFS='' read -r -d '' dockerfile <<"EOF"
FROM golang:alpine
LABEL maintainer "Ilya Glotov <ilya@ilyaglotov.com>"

ARG REPO

RUN apk --update --no-cache add git \
  && go get -ldflags="-s -w" $REPO \
  && apk del git \
  && adduser -D app

FROM alpine:latest
COPY --from=0 /go/bin/* /bin/
COPY --from=0 /etc/passwd /etc/passwd

USER app
EOF

<<< "$dockerfile" \
    docker build -t "$PKG_NAME" \
                 --build-arg "REPO=$PKG_PATH" \
                 -f - .

docker run -it \
           --rm \
           --entrypoint=/bin/${PKG_NAME} ${PKG_NAME} ${@:2}
